<h2>Account | add new user:</h2>
<a href="<?php echo $this->url('account'); ?>">&NestedLessLess; Back to Account</a>
<div class="left-block col-md-4 add-user" style="float: none; ">
    <?php echo $this->form()->openTag($this->form); ?>
        <?php foreach($this->form as $element) :  ?>
            <div class="wrapper-content-form">
                <?php if($element->getLabel()) : ?>
                    <label><?php echo $element->getLabel(); ?></label>
                <?php endif; ?>
                <?php echo $this->formElement($element); ?>
                <?php if($this->formElementErrors($element)) :  ?>
                    <div class="has-error">
                        <?php echo $this->formElementErrors($element) ?>
                    </div>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    <?php echo $this->form()->closeTag(); ?>
</div>